### ISSUE TITLE
Tests for Bibliography output

### ISSUE THREAD

**Issue by denismaier** [cormacrelf/jest-csl#2]
I am going to develop a bunch of styles for our institution in the next months. Most (if not all) of those styles have a bibliography, so it would be great if you could add tests for this. Having a test environment available would make this task much easier.

**Comment by cormacrelf** [comment]
Good news: this still looks pretty easy. I’ll see if I can get it out this weekend.

**Comment by denismaier** [comment]
Awesome!

**Comment by cormacrelf** [comment]
https://github.com/cormacrelf/jest-csl/blob/2534ebe1e55a04c6d39ca58b7a0a310216eb8320/__tests__/integration.yaml#L48-L60

**Comment by denismaier** [comment]
Amazing! Thank you very much. This helps a lot.
